/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formPackages;

import formPackages.classPackages.businessLayer;
import formPackages.classPackages.utility;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.beans.PropertyVetoException;
import java.io.InputStream;
import java.text.MessageFormat;
import java.util.HashMap;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author jo
 */
public class IntFrameGeneralSearch extends javax.swing.JInternalFrame {

    private static int flag=0;
    private boolean ALLOW_ROW_SELECTION =true;
    private int selectedRow;
    private String StudentReference_No;
    private String proc_DeletBeneficiary="{call Update_Data_Package.delete_Beneficiary(?,?)}";
    businessLayer busObj=new businessLayer();
    utility utilObj=new utility();
    
    public IntFrameGeneralSearch() {
        initComponents();
        
        prit_TblData(tblGeneralSearchBenficiary,btnPrintGeneralSearch);
        Tbl_SelectionMode(tblGeneralSearchBenficiary,"tblGeneralSearchBenficiary");
        PromptSupport.setPrompt("Enter Reference No...", txtMultiSearch);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        optRedioByReference = new javax.swing.JRadioButton();
        optRedioBySurName = new javax.swing.JRadioButton();
        optRedioByFirstName = new javax.swing.JRadioButton();
        btnSearch = new javax.swing.JButton();
        txtMultiSearch = new javax.swing.JTextField();
        btnPrintGeneralSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGeneralSearchBenficiary = new javax.swing.JTable(){

            public boolean isCellEditable(int rowIndex, int vColIndex) {
                return false;
            }
        };
        btnViewMorePersonlaDetail = new javax.swing.JButton();
        jDesktopPanePersonalDetail = new javax.swing.JDesktopPane();

        setClosable(true);
        setIconifiable(true);
        setTitle("Search Beneficiary");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/SearchSmall.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFont(new java.awt.Font("DejaVu Serif", 0, 12)); // NOI18N

        buttonGroup1.add(optRedioByReference);
        optRedioByReference.setFont(new java.awt.Font("DejaVu Serif", 0, 11)); // NOI18N
        optRedioByReference.setSelected(true);
        optRedioByReference.setText("By Reference ID");
        optRedioByReference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRedioByReferenceActionPerformed(evt);
            }
        });

        buttonGroup1.add(optRedioBySurName);
        optRedioBySurName.setFont(new java.awt.Font("DejaVu Serif", 0, 11)); // NOI18N
        optRedioBySurName.setText("By SurName");
        optRedioBySurName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRedioBySurNameActionPerformed(evt);
            }
        });

        buttonGroup1.add(optRedioByFirstName);
        optRedioByFirstName.setFont(new java.awt.Font("DejaVu Serif", 0, 11)); // NOI18N
        optRedioByFirstName.setText("By Given Name");
        optRedioByFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRedioByFirstNameActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SearchSmall.png"))); // NOI18N
        btnSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtMultiSearch.setFont(new java.awt.Font("DejaVu Serif", 0, 11)); // NOI18N
        txtMultiSearch.setToolTipText("");
        txtMultiSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtMultiSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMultiSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMultiSearchFocusLost(evt);
            }
        });
        txtMultiSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMultiSearchKeyPressed(evt);
            }
        });

        btnPrintGeneralSearch.setFont(new java.awt.Font("DejaVu Serif", 0, 11)); // NOI18N
        btnPrintGeneralSearch.setText("Print");
        btnPrintGeneralSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintGeneralSearchActionPerformed(evt);
            }
        });

        tblGeneralSearchBenficiary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "REFERENCE_NO", "SURNAME", "GIVEN NAME", "SEX"
            }
        ));
        jScrollPane1.setViewportView(tblGeneralSearchBenficiary);

        btnViewMorePersonlaDetail.setText("View More...");
        btnViewMorePersonlaDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMorePersonlaDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(optRedioByReference)
                .addGap(18, 18, 18)
                .addComponent(optRedioBySurName)
                .addGap(18, 18, 18)
                .addComponent(optRedioByFirstName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMultiSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrintGeneralSearch)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(594, 594, 594)
                                .addComponent(btnViewMorePersonlaDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optRedioByReference)
                    .addComponent(optRedioBySurName)
                    .addComponent(optRedioByFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(txtMultiSearch))
                    .addComponent(btnPrintGeneralSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewMorePersonlaDetail)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDesktopPanePersonalDetailLayout = new javax.swing.GroupLayout(jDesktopPanePersonalDetail);
        jDesktopPanePersonalDetail.setLayout(jDesktopPanePersonalDetailLayout);
        jDesktopPanePersonalDetailLayout.setHorizontalGroup(
            jDesktopPanePersonalDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPanePersonalDetailLayout.setVerticalGroup(
            jDesktopPanePersonalDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPanePersonalDetail))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPanePersonalDetail)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optRedioByReferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRedioByReferenceActionPerformed
        JRadioButton button = (JRadioButton) evt.getSource();

        if (button == optRedioByReference)  {
            txtMultiSearch.setText("");
            PromptSupport.setPrompt("Enter student reference No...", txtMultiSearch);
            flag=0;
        }
    }//GEN-LAST:event_optRedioByReferenceActionPerformed

    private void optRedioBySurNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRedioBySurNameActionPerformed
        JRadioButton button = (JRadioButton) evt.getSource();
        if (button == optRedioBySurName) {
            txtMultiSearch.setText("");
            PromptSupport.setPrompt("Enter beneficiary Surname...", txtMultiSearch);
            flag=1;
        }
    }//GEN-LAST:event_optRedioBySurNameActionPerformed

    private void optRedioByFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRedioByFirstNameActionPerformed
        JRadioButton button = (JRadioButton) evt.getSource();
        if (button == optRedioByFirstName) {
            txtMultiSearch.setText("");
            PromptSupport.setPrompt("Enter beneficiary given name...", txtMultiSearch);
            flag=2;
        }
    }//GEN-LAST:event_optRedioByFirstNameActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        if(flag==0) {

            // Fill Table
            busObj.pop_Talbe(tblGeneralSearchBenficiary, "select_Data_Package.get_BeneficiaryByReferenceNo(?,?)",
                txtMultiSearch.getText().trim());
            jScrollPane1.getViewport().add(tblGeneralSearchBenficiary);

        }else if(flag==1) {

            // Fill Table
            busObj.pop_Talbe(tblGeneralSearchBenficiary, "select_Data_Package.get_BeneficiaryBySurName(?,?)",
                txtMultiSearch.getText().trim());
            jScrollPane1.getViewport().add(tblGeneralSearchBenficiary);

        }else{

            // Fill Table
            busObj.pop_Talbe(tblGeneralSearchBenficiary, "select_Data_Package.get_BeneficiaryByGivenName(?,?)",
                txtMultiSearch.getText().trim());
            jScrollPane1.getViewport().add(tblGeneralSearchBenficiary);
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtMultiSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMultiSearchFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtMultiSearchFocusGained

    private void txtMultiSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMultiSearchFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtMultiSearchFocusLost

    private void txtMultiSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMultiSearchKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER) {
            if(flag==0) {

                // Fill Table
                busObj.pop_Talbe(tblGeneralSearchBenficiary, "select_Data_Package.get_BeneficiaryByReferenceNo(?,?)",
                    txtMultiSearch.getText().trim());
                jScrollPane1.getViewport().add(tblGeneralSearchBenficiary);
                

            }else if(flag==1) {

                // Fill Table
                busObj.pop_Talbe(tblGeneralSearchBenficiary, "select_Data_Package.get_BeneficiaryBySurName(?,?)",
                    txtMultiSearch.getText().trim());
                jScrollPane1.getViewport().add(tblGeneralSearchBenficiary);

            }else{

                // Fill Table
                busObj.pop_Talbe(tblGeneralSearchBenficiary, "select_Data_Package.get_BeneficiaryByGivenName(?,?)",
                    txtMultiSearch.getText().trim());
                jScrollPane1.getViewport().add(tblGeneralSearchBenficiary);
            }
             txtMultiSearch.setText(null);
             txtMultiSearch.grabFocus();
        }
    }//GEN-LAST:event_txtMultiSearchKeyPressed

    private void btnViewMorePersonlaDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMorePersonlaDetailActionPerformed
       try{
            HashMap parametersMap = new HashMap();  
           
                    
                    if(!(StudentReference_No==null)){
                        parametersMap.clear();
                        
                        parametersMap.put("studentID",StudentReference_No);
                       
                        generateReport("reports/personalDetail.jasper",parametersMap);
                        
                    }else 
                         JOptionPane.showMessageDialog(IntFrameGeneralSearch.this, "Please select the Beneficiary from the table",
                                 "Missing Beneficiary Selection", JOptionPane.ERROR_MESSAGE);
                }catch(Exception ex){}
    }//GEN-LAST:event_btnViewMorePersonlaDetailActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        utilObj.flag9=false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnPrintGeneralSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintGeneralSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintGeneralSearchActionPerformed

  private void Tbl_SelectionMode(final JTable table,final String tbl_Name){
           
    table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
                if (ALLOW_ROW_SELECTION) { // true by default
                  ListSelectionModel rowSM = table.getSelectionModel();
                  rowSM.addListSelectionListener(new ListSelectionListener() {
                    public void valueChanged(ListSelectionEvent e) {
                      // Ignore extra messages.
                      if (e.getValueIsAdjusting())
                        return;

                      ListSelectionModel lsm = (ListSelectionModel) e.getSource();
                    
                         if (!(lsm.isSelectionEmpty())){
                              selectedRow = lsm.getMinSelectionIndex();
                              printDebugData(table,selectedRow,tbl_Name);

                          }
                        
                    }
                  });
                } else {
                  table.setRowSelectionAllowed(false);
                }
             
    }
    
    private void printDebugData(JTable table,int selcted_Row,String tbl_Name) {
       try{ 
       // int numCols = table.getColumnCount();
        javax.swing.table.TableModel model = table.getModel();
      
                StudentReference_No=String.valueOf(model.getValueAt(selcted_Row, 0).toString());
         
        }catch(Exception ex){
            JOptionPane.showMessageDialog(IntFrameGeneralSearch.this, "The table is Empety ! Error: " + ex);
        }
  }
    
    public  void prit_TblData(final JTable table,JButton print_Button){
   
         ActionListener printAction = new ActionListener() {
          public void actionPerformed(ActionEvent e) {
            try {
           
              MessageFormat headerFormat = new MessageFormat("Kensington Community Learning Center");
              MessageFormat footerFormat = new MessageFormat("- {0} -");
          
              table.print(JTable.PrintMode.FIT_WIDTH, headerFormat,footerFormat, true, new  HashPrintRequestAttributeSet(), true);
               
            } catch (PrinterException pe) {
                JOptionPane.showMessageDialog(IntFrameGeneralSearch.this, "Error printing: " + pe.getMessage() );
             
            }
          }
        };
        print_Button.addActionListener(printAction);

    }
    
    public void generateReport(String fileName,HashMap parameter){
        try
            {
                InputStream in = this.getClass().getClassLoader()
                                .getResourceAsStream(fileName);
                    
            MyiReportViewer myiReportViewer = new MyiReportViewer(in,parameter);
            myiReportViewer.setBounds(0, 0, jDesktopPanePersonalDetail.getWidth(),
            jDesktopPanePersonalDetail.getHeight());
            myiReportViewer.setVisible(true);
            jDesktopPanePersonalDetail.add(myiReportViewer);
            myiReportViewer.setSelected(true);
            }
            catch (PropertyVetoException pve)
            {
            pve.printStackTrace();
            }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrintGeneralSearch;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewMorePersonlaDetail;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDesktopPane jDesktopPanePersonalDetail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton optRedioByFirstName;
    private javax.swing.JRadioButton optRedioByReference;
    private javax.swing.JRadioButton optRedioBySurName;
    private javax.swing.JTable tblGeneralSearchBenficiary;
    private javax.swing.JTextField txtMultiSearch;
    // End of variables declaration//GEN-END:variables
}
