/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formPackages;

import formPackages.classPackages.BarcodeGenerator;
import formPackages.classPackages.businessLayer;
import formPackages.classPackages.utility;
import java.io.File;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author jo
 */
public class IntFrameGenerateStudentID extends javax.swing.JInternalFrame {

    private static int flag=0;
    private boolean ALLOW_ROW_SELECTION =true;
    private int selectedRow;
    
    private List<String> selectedIDs ;
    
    DefaultListModel defList=new DefaultListModel();
    
    businessLayer busObj=new businessLayer();
    utility utilObj=new utility();
    BarcodeGenerator barCodeGenObj=new BarcodeGenerator();
    
    public IntFrameGenerateStudentID() {
        initComponents();
        PromptSupport.setPrompt("Enter Reference No...", txtMultiSearch);
        
        Tbl_SelectionMode(tblGeneralSearchBenficiary,"tblGeneralSearchBenficiary");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGeneralSearchBenficiary = new javax.swing.JTable(){

            public boolean isCellEditable(int rowIndex, int vColIndex) {
                return false;
            }
        };
        jPanel1 = new javax.swing.JPanel();
        optRedioByReference = new javax.swing.JRadioButton();
        optRedioBySurName = new javax.swing.JRadioButton();
        optRedioByFirstName = new javax.swing.JRadioButton();
        btnSearch = new javax.swing.JButton();
        txtMultiSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstListRefNumber = new javax.swing.JList();
        btnGenerateID = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Generate Student / Volunteer ID");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblGeneralSearchBenficiary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "REFERENCE_NO", "SURNAME", "GIVEN NAME"
            }
        ));
        jScrollPane1.setViewportView(tblGeneralSearchBenficiary);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(optRedioByReference);
        optRedioByReference.setFont(new java.awt.Font("DejaVu Serif", 0, 11)); // NOI18N
        optRedioByReference.setSelected(true);
        optRedioByReference.setText("By Reference ID");
        optRedioByReference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRedioByReferenceActionPerformed(evt);
            }
        });

        buttonGroup1.add(optRedioBySurName);
        optRedioBySurName.setFont(new java.awt.Font("DejaVu Serif", 0, 11)); // NOI18N
        optRedioBySurName.setText("By SurName");
        optRedioBySurName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRedioBySurNameActionPerformed(evt);
            }
        });

        buttonGroup1.add(optRedioByFirstName);
        optRedioByFirstName.setFont(new java.awt.Font("DejaVu Serif", 0, 11)); // NOI18N
        optRedioByFirstName.setText("By Given Name");
        optRedioByFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRedioByFirstNameActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SearchSmall.png"))); // NOI18N
        btnSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtMultiSearch.setFont(new java.awt.Font("DejaVu Serif", 0, 11)); // NOI18N
        txtMultiSearch.setToolTipText("");
        txtMultiSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtMultiSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMultiSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMultiSearchFocusLost(evt);
            }
        });
        txtMultiSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMultiSearchKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMultiSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(optRedioByReference)
                        .addGap(18, 18, 18)
                        .addComponent(optRedioBySurName)
                        .addGap(18, 18, 18)
                        .addComponent(optRedioByFirstName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optRedioByReference)
                    .addComponent(optRedioBySurName)
                    .addComponent(optRedioByFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMultiSearch)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lstListRefNumber.setFont(new java.awt.Font("DejaVu Serif", 0, 11)); // NOI18N
        lstListRefNumber.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstListRefNumberValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstListRefNumber);

        btnGenerateID.setFont(new java.awt.Font("DejaVu Serif", 0, 11)); // NOI18N
        btnGenerateID.setText("Generate Beneficiary ID");
        btnGenerateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateIDActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("DejaVu Serif", 0, 11)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGenerateID))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateID)
                    .addComponent(btnClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String get_selectedIDs(){ 
            String temp_String="";
       
            for (String v : selectedIDs) {
                     temp_String=temp_String + v +",";
                }
        
            return temp_String.substring(0, temp_String.length()-1);
      
    }
    private void optRedioByReferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRedioByReferenceActionPerformed
        JRadioButton button = (JRadioButton) evt.getSource();

        if (button == optRedioByReference)  {
            txtMultiSearch.setText("");
            PromptSupport.setPrompt("Enter student reference No...", txtMultiSearch);
            flag=0;
        }
    }//GEN-LAST:event_optRedioByReferenceActionPerformed

    private void optRedioBySurNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRedioBySurNameActionPerformed
        JRadioButton button = (JRadioButton) evt.getSource();
        if (button == optRedioBySurName) {
            txtMultiSearch.setText("");
            PromptSupport.setPrompt("Enter beneficiary Surname...", txtMultiSearch);
            flag=1;
        }
    }//GEN-LAST:event_optRedioBySurNameActionPerformed

    private void optRedioByFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRedioByFirstNameActionPerformed
        JRadioButton button = (JRadioButton) evt.getSource();
        if (button == optRedioByFirstName) {
            txtMultiSearch.setText("");
            PromptSupport.setPrompt("Enter beneficiary given name...", txtMultiSearch);
            flag=2;
        }
    }//GEN-LAST:event_optRedioByFirstNameActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        if(flag==0) {

            // Fill Table
            busObj.pop_Talbe(tblGeneralSearchBenficiary, "select_Data_Package.get_BeneficiaryByReferenceNo(?,?)",
                txtMultiSearch.getText().trim());
            jScrollPane1.getViewport().add(tblGeneralSearchBenficiary);

        }else if(flag==1) {

            // Fill Table
            busObj.pop_Talbe(tblGeneralSearchBenficiary, "select_Data_Package.get_BeneficiaryBySurName(?,?)",
                txtMultiSearch.getText().trim());
            jScrollPane1.getViewport().add(tblGeneralSearchBenficiary);

        }else{

            // Fill Table
            busObj.pop_Talbe(tblGeneralSearchBenficiary, "select_Data_Package.get_BeneficiaryByGivenName(?,?)",
                txtMultiSearch.getText().trim());
            jScrollPane1.getViewport().add(tblGeneralSearchBenficiary);
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtMultiSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMultiSearchFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtMultiSearchFocusGained

    private void txtMultiSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMultiSearchFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtMultiSearchFocusLost

    private void txtMultiSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMultiSearchKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER) {
            if(flag==0) {

                // Fill Table
                busObj.pop_Talbe(tblGeneralSearchBenficiary, "select_Data_Package.get_BeneficiaryByReferenceNo(?,?)",
                    txtMultiSearch.getText().trim());
                jScrollPane1.getViewport().add(tblGeneralSearchBenficiary);

            }else if(flag==1) {

                // Fill Table
                busObj.pop_Talbe(tblGeneralSearchBenficiary, "select_Data_Package.get_BeneficiaryBySurName(?,?)",
                    txtMultiSearch.getText().trim());
                jScrollPane1.getViewport().add(tblGeneralSearchBenficiary);

            }else{

                // Fill Table
                busObj.pop_Talbe(tblGeneralSearchBenficiary, "select_Data_Package.get_BeneficiaryByGivenName(?,?)",
                    txtMultiSearch.getText().trim());
                jScrollPane1.getViewport().add(tblGeneralSearchBenficiary);
            }
             txtMultiSearch.setText(null);
             txtMultiSearch.grabFocus();
                     
        }
    }//GEN-LAST:event_txtMultiSearchKeyPressed

    private void Tbl_SelectionMode(final JTable table,final String tbl_Name){
           
    table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
                if (ALLOW_ROW_SELECTION) { // true by default
                  ListSelectionModel rowSM = table.getSelectionModel();
                  rowSM.addListSelectionListener(new ListSelectionListener() {
                    public void valueChanged(ListSelectionEvent e) {
                      // Ignore extra messages.
                      if (e.getValueIsAdjusting())
                        return;

                      ListSelectionModel lsm = (ListSelectionModel) e.getSource();
                    
                         if (!(lsm.isSelectionEmpty())){
                              selectedRow = lsm.getMinSelectionIndex();
                              printDebugData(table,selectedRow,tbl_Name);
                              
                              lstListRefNumber.setModel(defList);

                          }
                        
                    }
                  });
                } else {
                  table.setRowSelectionAllowed(false);
                }
             
    }
    
    private void printDebugData(JTable table,int selcted_Row,String tbl_Name) {
       try{ 
       // int numCols = table.getColumnCount();
        javax.swing.table.TableModel model = table.getModel();
        String selectedRefID=String.valueOf(model.getValueAt(selcted_Row, 0).toString()) + 
                "-" + String.valueOf(model.getValueAt(selcted_Row, 1).toString()) +
                "-" + String.valueOf(model.getValueAt(selcted_Row, 2).toString()) ;
                
                if(!(hasElement(selectedRefID, lstListRefNumber)))
                    defList.addElement(selectedRefID);
                else
                    JOptionPane.showMessageDialog(IntFrameGenerateStudentID.this, "Student Reference allready selected , try other ");
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(IntFrameGenerateStudentID.this, "The table is Empety ! Error: " + ex);
        }
  }
    
    public static boolean hasElement(Object searched, JList list) {
      for (int a = 0; a < list.getModel().getSize(); a++) {
         Object element = list.getModel().getElementAt(a);
         if (element.equals(searched))  {
            return true;
         }
      }
      return false;
   }
    
    private void btnGenerateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateIDActionPerformed
        String fileName="beneficiaryIDs.pdf"; 
        if(!(selectedIDs==null))
        barCodeGenObj.BarcodeGeneratorOpen(fileName, get_selectedIDs());
        else JOptionPane.showMessageDialog(IntFrameGenerateStudentID.this,"One or More Beneficiary should be selected from the list !!");
             
    }//GEN-LAST:event_btnGenerateIDActionPerformed

    private void lstListRefNumberValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstListRefNumberValueChanged
                if(!evt.getValueIsAdjusting()) {
                     selectedIDs=lstListRefNumber.getSelectedValuesList();
                   }
    }//GEN-LAST:event_lstListRefNumberValueChanged

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        utilObj.flag8=false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       
        DefaultListModel listModel = (DefaultListModel) lstListRefNumber.getModel();
        listModel.removeAllElements();
   
    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerateID;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstListRefNumber;
    private javax.swing.JRadioButton optRedioByFirstName;
    private javax.swing.JRadioButton optRedioByReference;
    private javax.swing.JRadioButton optRedioBySurName;
    private javax.swing.JTable tblGeneralSearchBenficiary;
    private javax.swing.JTextField txtMultiSearch;
    // End of variables declaration//GEN-END:variables
}
